application: cmcquatt2
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /resources
  static_dir: resources
- url: /.*
  script: blog_main.py
  
libraries:
- name: jinja2
  version: latest
- name: markupsafe                                                              
  version: latest


